// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// isglasso
Rcpp::List isglasso(const arma::mat& X_t, const arma::mat& y_t, const arma::mat& X_v, const arma::mat& y_v, const arma::vec& grp_len, const int num_iter, const int loss, const int metric, const int regularization);
RcppExport SEXP _ishpR_isglasso(SEXP X_tSEXP, SEXP y_tSEXP, SEXP X_vSEXP, SEXP y_vSEXP, SEXP grp_lenSEXP, SEXP num_iterSEXP, SEXP lossSEXP, SEXP metricSEXP, SEXP regularizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_t(X_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_t(y_tSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_v(X_vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_v(y_vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type grp_len(grp_lenSEXP);
    Rcpp::traits::input_parameter< const int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type loss(lossSEXP);
    Rcpp::traits::input_parameter< const int >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< const int >::type regularization(regularizationSEXP);
    rcpp_result_gen = Rcpp::wrap(isglasso(X_t, y_t, X_v, y_v, grp_len, num_iter, loss, metric, regularization));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ishpR_isglasso", (DL_FUNC) &_ishpR_isglasso, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_ishpR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
