# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isglasso <- function(X_t, y_t, X_v, y_v, grp_len, num_iter, loss, metric, regularization) {
    .Call(`_ishpR_isglasso`, X_t, y_t, X_v, y_v, grp_len, num_iter, loss, metric, regularization)
}

